apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "member-net-controller-manager.fullname" . }}-sa
  namespace: {{ .Values.fleetSystemNamespace }}
  labels:
    {{- include "member-net-controller-manager.labels" . | nindent 4 }}
  {{- if .Values.azure.workloadIdentityEnabled }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.azure.clientid | quote }}
  {{- end }}
