apiVersion: v1
kind: ServiceAccount
metadata:
  name: hub-gateway-controller-manager
  namespace: {{ .Values.fleetSystemNamespace }}
  annotations:
    azure.workload.identity/client-id: {{ required "azure.clientId is required" .Values.azure.clientId | quote }}
